apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-deployment
  namespace: task-manager
  labels:
    app: task-manager
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
      - name: task-manager
        image: pavansaipashikanti/task-manager:latest
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10

        envFrom:
        - configMapRef:
            name: task-manager-config

        # env:
        # - name: REDIS_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: task-manager-config
        #       key: REDIS_HOST
            
        # - name: REDIS_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: task-manager-config
        #       key: REDIS_PORT

        # - name: PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: task-manager-config
        #       key: PORT

        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
